- name: Create S3 bucket
  s3_bucket:
    name: "{{bucket_name}}"
    state: present
    region: "{{aws_region}}"
  register: s3_bucket_name

- name: Print bucket name
  debug:
    var: s3_bucket_name    
