- name : Copy file
  copy:
    src: ~/ansible-playbooks/s3_using_ansible/roles/s3_bucket_policy/template/policy.json.org
    dest: ~/ansible-playbooks/s3_using_ansible/roles/s3_bucket_policy/template/policy.json
    mode: '0644'
- name: replce the word from the file
  #shell: sed -i 's/bucket_name/"{{ bucket_name}}"/' files/policy.json
  replace:
    path: ~/ansible-playbooks/s3_using_ansible/roles/s3_bucket_policy/template/policy.json
    regexp: bucket_name
    replace: "{{ bucket_name }}"
    #backup: yes

- name: Set bucket policy
  aws_s3:
    bucket: "{{ bucket_name }}"
    region: "{{ aws_region }}"
    policy: "{{ lookup( 'file','~/ansible-playbooks/s3_using_ansible/roles/s3_bucket_policy/template/policy.json' )}}"
    #state: present
    #versioning: no
