-   name: Create an EC2 instance
    ec2:
        key_name: "{{ key_pair }}"
        region: "{{ aws_region }}"
        group_id: "{{ group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: yes
        instance_tags:
            Name: " {{ ins_name }}"
            env: "{{ env }}"
        volumes:
         - device_name: /dev/sda1
           volume_size: "{{ vol_size }}"
           device_type: "{{vol_type}}"
           delete_on_termination: True
        monitoring: no
        count_tag: env
        exact_count: 1
#        instance_profile_arn: "{{ role_arn }}"
#        user_data: "{{user_data_path}}/user_data_bootstrap.txt"
        vpc_subnet_id: "{{ subnet }}"
    register: ec2 

