- name: Download files to S3 bucket
  aws_s3:
    bucket: "{{ bucket_name }}"
    region: "{{ aws_region }}"
    #upload: yes
    mode: get
    object: "{{ file_name }}"
    #src: "{{ src_path }}"
    dest: "{{ dest_path }}"

