- name: Upload files to S3 bucket
  aws_s3:
    bucket: "{{ bucket_name }}"
    region: "{{ aws_region }}"
    #upload: yes
    mode: put
    object: "{{ file_name }}"
    src: "{{ src_path }}"
    dest: "{{ dest_path }}"

